name: Deploy Static Project

on:
  push:
    branches:
      - main
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem -o StrictHostKeyChecking=no \
          $SSH_USER@$SSH_HOST << 'EOF'

            cd /var/www/html

            echo "Updating static site..."

            git fetch origin
            git reset --hard origin/main

            echo "Done deploying static site."

          EOF

      - name: Cleanup
        run: rm -f private_key.pem