name: Deploy Static Project

on:
  push:
    branches:
      - main
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no \
          "${EC2_USERNAME}@${EC2_HOST}" << 'EOF'

            cd /var/www/html

            echo "Deploy start....."

            git fetch origin
            git reset --hard origin/main

            echo "Done deploying static site."

          EOF

      - name: Cleanup SSH key
        if: always()
        run: rm -f private_key.pem